spring:
  application:
    name: "SpringTemplate"
  flyway:
    enabled: true
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    url: ${spring.datasource.url}
    baseline-on-migrate: true

mybatis:
  mapper-locations: classpath:db/mapper/**/*.xml

config:
  swagger:
    show: false

jwt:
  issuer: "Kazuhiro Oka"
