name: Test

on:
  pull_request:
  push:
    branches: [ develop ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    if: github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up database
        uses: shogo82148/actions-setup-mysql@v1
        with:
          mysql-version: "8.0"

      - name: Prepare database
        run: |
          mysql -u root < ${{ github.workspace }}/.github/ci_setup.sql

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '21'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Create config file
        run: |
          cat << 'EOF' > src/main/resources/application-test.yml
          ${{ secrets.APPLICATION_TEST_YML }}
          EOF

      - name: Test
        run: mvn integration-test
